---
- name: setup Linux host to connect to the domain
  hosts: linux
  become: true
  gather_facts: false
  module_defaults:
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600

  pre_tasks:
    - name: wait for connection to come online
      ansible.builtin.wait_for_connection:

    - name: ensure base packages are installed
      ansible.builtin.package:
        name:
          - vim
          - git
          # fix for chmod: invalid mode: ‘A+user:ansible:rx:allow’
          - acl
        state: latest

    - name: ensure libselinux-python3 and python3-packaging is installed for dnf
      ansible.builtin.dnf:
        name:
          - libselinux-python3
          - python3-packaging
        state: present
      when: ansible_package_name == 'dnf'

  roles:
    - role: user-setup
    - role: kerberos
    - role: python
      vars:
        man_python_version: '{{python3_version}}'

- name: setup pip and Ansible for the ansible user
  hosts: all
  become: true
  become_user: '{{man_user_setup_user}}'
  gather_facts: false
  roles:
    - ansible-setup
